name: Build DLL Online

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      
    - name: Restore NuGet Packages
      run: nuget restore

    - name: Build Solution
      run: msbuild /p:Configuration=Release

    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: My-Built-DLL
        path: "**/bin/Release/**/*.dll"
